export const AUTH = "auth"
export const AUTH_HUMAN_PENDING = "AUTH_HUMAN_PENDING";
export const AUTH_GETTOKEN_HUMAN = "AUTH_GETTOKEN_HUMAN";
export const AUTH_HUMAN_ERROR = "AUTH_HUMAN_ERROR";
export const AUTH_GETDATA_HUMAN =  "AUTH_GETDATA_HUMAN"
