export const STATUSES = "statuses"
export const FETCH_STATUSES_PENDING = "FETCH_STATUSES_PENDING";
export const FETCH_STATUSES_SUCCESS = "FETCH_STATUSES_SUCCESS";
export const FETCH_STATUSES_ERROR = "FETCH_STATUSES_ERROR";
